# Generated by Django 5.1.2 on 2024-10-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.IntegerField(default=0)),
                ("subtitle", models.IntegerField(default=0)),
                ("content", models.IntegerField(default=0)),
                ("links", models.JSONField(default=list)),
            ],
        ),
    ]
